#!/bin/bash
#PBS -q development
#PBS -N CUDAThrust
#PBS -l select=1:ncpus=1:ngpus=1
#PBS -l place=free
#PBS -V

# Find out name of master execution host (compute node)
echo -n ">>>> PBS Master compute node is: "
hostname

# You must explicitly change to the working directory in PBS
cd $PBS_O_WORKDIR

# Point to the CUDA Thrust executable to run the job
echo ">>>> Begin run ..."
echo ""
./cuda-thrust
echo ""
echo ">>>> End run."
